export const GET_LIST_PRODUCT_REQUEST = 'GET_LIST_PRODUCT_REQUEST';
export const GET_LIST_PRODUCT_SUCCESS = 'GET_LIST_PRODUCT_SUCCESS';
export const GET_LIST_PRODUCT_ERROR = 'GET_LIST_PRODUCT_ERROR';
export const PAGINATION = 'PAGINATION';

export const GET_LIST_PRODUCT_DETAIL_REQUEST = 'GET_LIST_PRODUCT_DETAIL_REQUEST';
export const GET_LIST_PRODUCT_DETAIL_SUCCESS = 'GET_LIST_PRODUCT_DETAIL_SUCCESS';
export const GET_LIST_PRODUCT_DETAIL_ERROR = 'GET_LIST_PRODUCT_DETAIL_ERROR';