export const GET_LIST_PRODUCT_REQUEST = 'GET_LIST_PRODUCT_REQUEST';
export const GET_LIST_PRODUCT_SUCCESS = 'GET_LIST_PRODUCT_SUCCESS';
export const GET_LIST_PRODUCT_ERROR = 'GET_LIST_PRODUCT_ERROR';
export const PAGINATION = 'PAGINATION';

export const GET_LIST_PRODUCT_DETAIL_REQUEST = 'GET_LIST_PRODUCT_DETAIL_REQUEST';
export const GET_LIST_PRODUCT_DETAIL_SUCCESS = 'GET_LIST_PRODUCT_DETAIL_SUCCESS';
export const GET_LIST_PRODUCT_DETAIL_ERROR = 'GET_LIST_PRODUCT_DETAIL_ERROR';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';
export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_ERROR = 'ORDER_ERROR';